#!/bin/bash

echo "Warning: tags are not implemented yet, always pulling from HEAD"

checkout() {
  if [ -d "$1" ]; then
    pushd $1 > /dev/null
    echo "pulling $1"
    git pull
    popd > /dev/null
  else
    echo "cloning $1"
    git clone https://github.com/$REPO.git $1
  fi
}

unpack() {
  echo "unpacking $2 into $3"
  for DIR in $2/*/; do
    mkdir -p $3/`basename $DIR`/$1
    cp -R $DIR/* $3/`basename $DIR`/$1
  done
}

JSON=`cat infection.json | tr -d '[\r\n]' | JSON.sh`

INFECT=`echo "$JSON" | grep '\["infect"\]' | cut -f 2 | tr -d "[\'\"]"`
WITH=`echo "$JSON" | grep '\["with"\]' | cut -f 2 | sed -e 's/[{}]//g' | tr -d "[\'\"]"`

IFS=','
for with in $WITH ; do
  unset IFS
  
  REPO=`echo $with | cut -d: -f1`
  TAG=`echo $with | cut -d: -f2`
  
  checkout "packages/$REPO"
done

for PACKAGE in ./packages/*/*/; do
  PACKAGEROOT=`cat $PACKAGE/infection.json | tr -d '[\r\n]' | JSON.sh | grep '\["infect"\]' | cut -f 2 | tr -d "[\'\"]"`

  unpack $PACKAGE $PACKAGE$PACKAGEROOT $INFECT
done
